In [1]:
import numpy as np
a = np.array([1,2,3]) # passed as list
b = np.array((1,2,3)) # passed as tupple
print(a)
print(b)

[1 2 3]
[1 2 3]


In [2]:
b[1] = 4 # array using numpy is editable
b

array([1, 4, 3])

In [3]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [4]:
c[0]

array([1, 2, 3])

In [5]:
c[1]

array([4, 5, 6])

In [6]:
a[0:]

array([1, 2, 3])

In [8]:
b[0:]

array([1, 4, 3])

In [9]:
type(a)

numpy.ndarray

In [10]:
d = np.zeros((3,4)) # np.zeros((row,column))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
e = np.arange(10,25,5)
print(e)

[10 15 20]


In [12]:
# np.arrange(startnum,endnum,interval)
# startnum till endnum-interval
f = np.arange(10,20,2)
print(f)

[10 12 14 16 18]


In [13]:
# np.linspace(startnum,endnum,numberofpoints)
g = np.linspace(5,6,10)
print(g)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [14]:
# Creating array with same number
# np.full((rownum,colnum,numbertofill))
h = np.full((3,4),5)
print(h)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
i = np.random.random((3,4))
print(i)

[[0.63288678 0.66020983 0.11121014 0.46794838]
 [0.93570833 0.9835373  0.11345945 0.14555243]
 [0.34321112 0.84730637 0.47907846 0.69096039]]


In [16]:
print(h.shape) # np.array.shape return tuple (rownum, colnum)

(3, 4)


In [17]:
j = np.array([[1,2,3],[4,5,6]])
print("Before :", j)
j.shape = (3,2)
print("After :",j)

Before : [[1 2 3]
 [4 5 6]]
After : [[1 2]
 [3 4]
 [5 6]]


In [18]:
print(j.shape[0])
print(j.shape[1])

3
2


In [19]:
# np.arange(numberofpointsneeded)
# will place the number between 0 till (that number -1)
k = np.arange(24)
print(k)
print(k.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
24


In [20]:
print(j.shape) # returns shape of the array
print(j.ndim) # returns dimension of the array
print(j.dtype) # returns type of elements in the array (Homogenous Array)

(3, 2)
2
int32


In [21]:
l = np.linspace(5,7,11)
print(l)

[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]


In [22]:
m = np.array([5,10])
print('result of np.sum(m)-',np.sum(m))
print('result of sum(m)-',sum(m))


result of np.sum(m)- 15
result of sum(m)- 15


In [23]:
n = np.array([2,3])
print(np.subtract(m,n)) # subtract two arrays
print(np.add(m,n)) # add two arrays

[3 7]
[ 7 13]


In [24]:
np.sum([m,n], axis = 1)

array([15,  5])

In [25]:
print(np.divide(m,n))

[2.5        3.33333333]


In [26]:
print(np.multiply(m,n))

[10 30]


In [27]:
print(np.exp(m))

[  148.4131591  22026.46579481]


In [28]:
print(np.sqrt(m))

[2.23606798 3.16227766]


In [29]:
print(np.sin(m))

[-0.95892427 -0.54402111]


In [30]:
print(np.cos(m))

[ 0.28366219 -0.83907153]


In [31]:
print(np.log(m))

[1.60943791 2.30258509]


In [32]:
o = [1,2,3]
p = [1,2,3]
q = [4,5,6]

print('comparision between o and p -', np.equal(o,p))
print('comparision between o and q -', np.equal(o,q))

comparision between o and p - [ True  True  True]
comparision between o and q - [False False False]


In [33]:
print(np.array_equal(o,p))
print(np.array_equal(o,q))

True
False


In [34]:
r = np.array([1,2,3])
print(np.sum(r))
print(np.min(r))
print(np.max(r))
print(np.mean(r))
print(np.std(r))
print(np.median(r))
print(np.corrcoef(r))

6
1
3
2.0
0.816496580927726
2.0
1.0


In [35]:
s = np.array([[1,2,3],[4,5,6]])
print(np.sum(s))
print(np.min(s))
print(np.max(s))
print(np.mean(s))
print(np.std(s))
print(np.median(s))
print(np.corrcoef(s))

21
1
6
3.5
1.707825127659933
3.5
[[1. 1.]
 [1. 1.]]


In [37]:
t = np.array([[1,2,3],[4,5,6]])
u = np.array([3,4,5])
print(t)
print(u)
print(np.sum([t,u]))
print(np.subtract(t,u))
print(np.add(t,u))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [ 1  1  1]]
[[ 4  6  8]
 [ 7  9 11]]


In [38]:
np.equal(np.sum([t,u]),np.add(t,u)) # np.sum & np.add comparission to check result of both are same

array([[ True,  True,  True],
       [ True,  True,  True]])

In [39]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('First result', v[0])
print('Second result', v[:1])
print('Third result', v[1])
print('forth result', v[1:])

First result [1 2 3]
Second result [[1 2 3]]
Third result [4 5 6]
forth result [[4 5 6]
 [7 8 9]]


In [85]:
print(v[0:]) # v[0:] displays all elements from r0 to r(n-1) of n dimentional matrix
print(v[1:]) # v[1:] displays all elements from r1 and r(n-1) of n dimentional matrix
print(v[2:]) # v[2:] displays all elements from r2 and r(n-1) of n dimentional matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[7 8 9]]


In [86]:
# v[3:] displays all elements from r3 and r(n-1) of n dimentional matrix
# result will be blank array since v is 3 dimentional matrix and hence there is only r0 to r2. 
# No r3 available for array v
print(v[3:]) 

[]


In [89]:
print(v[:1]) # v[:1] displays all elements of r0
print(v[:2]) # v[:2] displays all elements of r0 and r1
print(v[:3]) # v[:3] displays all elements of r0, r1 and r2

[[1 2 3]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
# v[:4] displays all elements of r0 to r3. 
# Here in v array there is only 3 rows r0 to r2. Hence for v[:n] where n >= 3 the output is same as v[:3]
print(v[:6])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
print(v[1:,1:]) # displays elements from r1&r2 and c1&c2

[[5 6]
 [8 9]]


In [99]:
print(v[:1,:1]) # displays element from r0 and c0

[[1]]


In [102]:
print(v[1:,:1]) # displays elements from r1&r2 and c0
print(v[2:,:2]) # displays elements from r2 and c0&c1

[[4]
 [7]]
[[7 8]]


In [104]:
print(v[2:,:1]) # displays elements from r2 and c0
print(v[2:,:3]) # displays elements from r2 and c0,c1&c2

[[7]]
[[7 8 9]]


In [111]:
w = np.array([[1,2,3],[4,5,6]])
x = np.array([[3,4,5],[6,7,8]])

In [110]:
np.concatenate([w,x], axis=0) # array w and x are row-wise stacked when axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
np.concatenate([w,x], axis=1) # array w and x are column-wise stacked when axis = 1

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 6, 7, 8]])

In [129]:
y = [1,2,3]
z = [4,5,6]

In [119]:
# stack only takes 1D array into account
print(np.stack((y,z), axis=0)) # row-wise stacked when axis = 0 
print(np.stack((y,z), axis=1)) # column-wise stacked when axis = 1

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [127]:
print(np.hstack((w,x))) # Horizontal stacking

[[1 2 3 3 4 5]
 [4 5 6 6 7 8]]


In [122]:
print(np.vstack((w,x))) # Vertical stacking

[[1 2 3]
 [4 5 6]
 [3 4 5]
 [6 7 8]]


In [132]:
# np.split(array,index,axis)
# where array can be any numpy array
# where index can be either integer or list. 

aa = np.array([[1,2,3],[4,5,6]])
print('The array is-------')
print(aa)
print('result when array is splitted----')
print(np.split(aa,2,axis = 0)) # split the array aa into 2 arrays. Axis = 0 : split based on rows

The array is-------
[[1 2 3]
 [4 5 6]]
result when array is splitted----
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [136]:
print(np.split(aa,3,axis = 1)) # split the array aa into 3 arrays. Axis = 1 : split based on columns

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [141]:
print(np.split(aa,[1,2],axis = 0)) # result of the split will be 3 arrays. Axis = 0 : split based on rows
# 1st array = aa[:1]
# 2nd array = aa[1:2]
# 3rd array = aa[2:]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [150]:
print(np.split(aa,[1,2],axis = 1)) # result of the split will be 3 arrays. Axis = 1 : split based on columns
# 1st array = aa[:,:1]
# 2nd array = aa[:,1:2]
# 3rd array = aa[:,2:]

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [154]:
# Numpy Vs List - memory size
import sys

# Define list
x_list = range(1000)
print('Size of the list is ', sys.getsizeof(x_list)*len(x_list))

# Define a numpy array
x_array = np.arange(1000)
print('Size of the numpy array is ', x_array.size*x_array.itemsize)


Size of the list is  48000
Size of the numpy array is  4000


In [162]:
# Numpy Vs List - Speed
import time

# Define list
def using_list():
    t1 = time.time() # Initializing Time
    X = range(1000000)
    Y = range(1000000)
    Z = [X[i] +Y[i] for i in range(len(X))]
    return time.time() - t1


def using_numpy():
    t1 = time.time() # Initializing Time
    X = np.arange(1000000)
    Y = np.arange(1000000)
    Z = X + Y
    return time.time() - t1

list_time = using_list()
numpy_time = using_numpy()

print("In this example numpy is " + str(list_time/numpy_time) + " times faster than list")

In this example numpy is 60.091225357557015 times faster than list
